CREATE TABLE usuarios(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    data_criacao TIMESTAMPTZ,
    data_atualizacao TIMESTAMPTZ

);

CREATE TABLE contatos(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50),
    telefone VARCHAR(20),
    cliente_id BIGINT,
    CONSTRAINT fk_contatos_usuarios FOREIGN KEY (cliente_id) REFERENCES usuarios(id)
);